In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('../votacoes_full_with_communities_complete.csv')
df

,id,data,idOrgao,siglaOrgao,aprovacao,votosSim,votosNao,votosOutros,descricao,ano,...,orientacao_GOV,tipoAutor,idDeputadoAutor,nomeAutor,data_ref,legislatura,author_prev_community,prev_community_0_size,prev_community_1_size,prev_community_2_size
0,103255-3,2003-02-19,180,PLEN,1.0,0,0,0,Aprovado o Requerimento,2003,...,Neutro,Deputado(a),74218.0,Walter Pinheiro,1,52,NaN,NaN,NaN,0
1,102277-6,2003-02-19,180,PLEN,1.0,0,0,0,Aprovado requerimento n. 264/2002 de Líderes q...,2003,...,Neutro,Deputado(a),74218.0,Walter Pinheiro,1,52,NaN,NaN,NaN,0
2,105029-15,2003-03-18,180,PLEN,1.0,0,0,0,Aprovado REQ 450/2003 do Sr. Maurício Rabelo q...,2003,...,Neutro,Deputado(a),73947.0,Maurício Rabelo,8,52,NaN,NaN,NaN,0
3,107184-2,2003-03-18,180,PLEN,1.0,0,0,0,Aprovado o Requerimento,2003,...,Neutro,Deputado(a),73947.0,Maurício Rabelo,8,52,NaN,NaN,NaN,0
4,19701-51,2003-03-20,180,PLEN,1.0,0,0,0,"Aprovado o Projeto de Lei nº 3.462, de 2000, r...",2003,...,Neutro,Deputado(a),74082.0,Paulo Rocha,10,52,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78809,347421-202,2024-12-19,180,PLEN,NaN,4,360,1,Suprimido o texto. Sim: 4; Não: 360; Total: 364.,2024,...,Não,Deputado(a),73778.0,Luiz Carlos Hauly,1889,57,NaN,441.0,155.0,0
78810,347421-202,2024-12-19,180,PLEN,NaN,4,360,1,Suprimido o texto. Sim: 4; Não: 360; Total: 364.,2024,...,Não,Deputado(a),74283.0,Vicentinho,1889,57,1.0,441.0,155.0,0
78811,347421-202,2024-12-19,180,PLEN,NaN,4,360,1,Suprimido o texto. Sim: 4; Não: 360; Total: 364.,2024,...,Não,Deputado(a),141531.0,Rodrigo de Castro,1889,57,0.0,441.0,155.0,0
78812,347421-205,2024-12-19,180,PLEN,NaN,349,143,1,Mantido o texto. Sim: 349; Não: 143; Abstenção...,2024,...,Sim,Deputado(a),74063.0,Fernando de Fabinho,1889,57,NaN,441.0,155.0,0
78813,2473375-80,2024-12-19,180,PLEN,1.0,0,0,0,Aprovada a Redação Final assinada pelo relator...,2024,...,Neutro,Deputado(a),160674.0,Hugo Motta,1889,57,0.0,441.0,155.0,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78818 entries, 0 to 78817
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     78818 non-null  object
 1   data                   78818 non-null  object
 2   idOrgao                78818 non-null  int64
 3   siglaOrgao             78818 non-null  object
 4   aprovacao              78818 non-null  float64
 5   votosSim               78818 non-null  int64
 6   votosNao               78818 non-null  int64
 7   votosOutros            78818 non-null  int64
 8   descricao              78818 non-null  object
 9   ano                    78818 non-null  int64
 10  proposicao_id          78818 non-null  int64
 11  proposicao_ementa      78818 non-null  object
 12  id_proposicao          78818 non-null  float64
 13  tema                   78818 non-null  object
 14  orientacao_GOV         78818 non-null  object
 15  tipoAutor              78818 non-null  object
 16  idDeputadoAutor        78818 non-null  float64
 17  nomeAutor              78818 non-null  object
 18  data_ref               78818 non-null  int64
 19  legislatura            78818 non-null  int64
 20  author_prev_community  43399 non-null  float64
 21  prev_community_0_size  73174 non-null  float64
 22  prev_community_1_size  73174 non-null  float64
 23  prev_community_2_size  78818 non-null  int64
 24  classified_llm         30263 non-null  object
 25  authors_pop            13627 non-null  float64
dtypes: float64(7), int64(9), object(10)
memory usage: 15.6+ MB

In [18]:
df.describe()

,idOrgao,aprovacao,votosSim,votosNao,votosOutros,ano,proposicao_id,id_proposicao,idDeputadoAutor,data_ref,legislatura,author_prev_community,prev_community_0_size,prev_community_1_size,prev_community_2_size,authors_pop
count,78818.0,78818.000000,78818.000000,78818.000000,78818.000000,78818.000000,7.881800e+04,7.881800e+04,78818.000000,78818.000000,78818.000000,43399.000000,73174.000000,73174.000000,78818.000000,13627.000000
mean,180.0,0.713923,84.928316,51.659786,2.477302,2017.477175,1.559820e+06,1.559820e+06,138069.558844,1275.203697,55.318328,0.468697,375.176087,225.517137,0.417265,0.878400
std,0.0,0.451929,141.010896,102.945698,10.135753,6.761959,9.545403e+05,9.545403e+05,58363.175457,579.611149,1.660088,0.499948,45.060608,48.096021,1.778778,0.214304
min,180.0,0.000000,0.000000,0.000000,0.000000,2003.000000,1.802000e+04,1.802000e+04,3151.000000,1.000000,52.000000,0.000000,330.000000,155.000000,0.000000,0.000000
25%,180.0,0.000000,0.000000,0.000000,0.000000,2012.000000,3.304270e+05,3.304270e+05,74324.000000,778.000000,54.000000,0.000000,348.000000,155.000000,0.000000,0.800000
50%,180.0,1.000000,0.000000,0.000000,0.000000,2021.000000,2.242583e+06,2.242583e+06,141503.000000,1503.000000,56.000000,0.000000,348.000000,252.000000,0.000000,1.000000
75%,180.0,1.000000,128.000000,23.000000,1.000000,2023.000000,2.301088e+06,2.301088e+06,204396.000000,1779.000000,57.000000,1.000000,441.000000,262.000000,0.000000,1.000000
max,180.0,1.000000,505.000000,445.000000,176.000000,2024.000000,2.479834e+06,2.479834e+06,228837.000000,1889.000000,57.000000,2.000000,441.000000,274.000000,8.000000,1.000000

In [12]:
import os

# Path to the folder containing the classified datasets
classified_folder = os.path.join("..", "..", "..", "data", "classified_llm_datasets")

# Initialize an empty list to store DataFrames
classified_dfs = []

# There are 88 files, named classified_voting_texts_batch_{index}.csv
for idx in range(1, 89):
    file_path = os.path.join(classified_folder, f"classified_voting_texts_batch_{idx}.csv")
    if os.path.exists(file_path):
        temp_df = pd.read_csv(file_path, dtype={'idVotacao': str})
        classified_dfs.append(temp_df[['idVotacao', 'classification']])
    else:
        print(f"Warning: {file_path} does not exist.")

# Concatenate all classified DataFrames if any were loaded
if classified_dfs:
    classified_all = pd.concat(classified_dfs, ignore_index=True)

    # Ensure the id columns are strings for matching
    df['id'] = df['id'].astype(str)
    classified_all['idVotacao'] = classified_all['idVotacao'].astype(str)

    # Merge the classification into the main df
    df = df.merge(classified_all, how='left', left_on='id', right_on='idVotacao')

    # Rename the column to classified_llm and drop the helper column
    df.rename(columns={'classification': 'classified_llm'}, inplace=True)
    df.drop(columns=['idVotacao'], inplace=True)
else:
    print("No classified datasets were loaded. The 'classified_llm' column will not be added.")

df.tail(5)

,id,data,idOrgao,siglaOrgao,aprovacao,votosSim,votosNao,votosOutros,descricao,ano,...,tipoAutor,idDeputadoAutor,nomeAutor,data_ref,legislatura,author_prev_community,prev_community_0_size,prev_community_1_size,prev_community_2_size,classified_llm
78813,347421-202,2024-12-19,180,PLEN,NaN,4,360,1,Suprimido o texto. Sim: 4; Não: 360; Total: 364.,2024,...,Deputado(a),73778.0,Luiz Carlos Hauly,1889,57,NaN,441.0,155.0,0,NaN
78814,347421-202,2024-12-19,180,PLEN,NaN,4,360,1,Suprimido o texto. Sim: 4; Não: 360; Total: 364.,2024,...,Deputado(a),74283.0,Vicentinho,1889,57,1.0,441.0,155.0,0,NaN
78815,347421-202,2024-12-19,180,PLEN,NaN,4,360,1,Suprimido o texto. Sim: 4; Não: 360; Total: 364.,2024,...,Deputado(a),141531.0,Rodrigo de Castro,1889,57,0.0,441.0,155.0,0,NaN
78816,347421-205,2024-12-19,180,PLEN,NaN,349,143,1,Mantido o texto. Sim: 349; Não: 143; Abstenção...,2024,...,Deputado(a),74063.0,Fernando de Fabinho,1889,57,NaN,441.0,155.0,0,NaN
78817,2473375-80,2024-12-19,180,PLEN,1.0,0,0,0,Aprovada a Redação Final assinada pelo relator...,2024,...,Deputado(a),160674.0,Hugo Motta,1889,57,0.0,441.0,155.0,0,Approval of Final Wording

In [13]:
nan_count = df['classified_llm'].isna().sum()
not_nan_count = df['classified_llm'].notna().sum()
print(f"NaN count in 'classified_llm': {nan_count}")
print(f"Not NaN count in 'classified_llm': {not_nan_count}")

NaN count in 'classified_llm': 48555
Not NaN count in 'classified_llm': 30263

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78818 entries, 0 to 78817
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     78818 non-null  object
 1   data                   78818 non-null  object
 2   idOrgao                78818 non-null  int64
 3   siglaOrgao             78818 non-null  object
 4   aprovacao              75625 non-null  float64
 5   votosSim               78818 non-null  int64
 6   votosNao               78818 non-null  int64
 7   votosOutros            78818 non-null  int64
 8   descricao              78818 non-null  object
 9   ano                    78818 non-null  int64
 10  proposicao_id          78818 non-null  int64
 11  proposicao_ementa      78818 non-null  object
 12  id_proposicao          78818 non-null  float64
 13  tema                   78818 non-null  object
 14  orientacao_GOV         78818 non-null  object
 15  tipoAutor              78818 non-null  object
 16  idDeputadoAutor        78818 non-null  float64
 17  nomeAutor              78818 non-null  object
 18  data_ref               78818 non-null  int64
 19  legislatura            78818 non-null  int64
 20  author_prev_community  43399 non-null  float64
 21  prev_community_0_size  73174 non-null  float64
 22  prev_community_1_size  73174 non-null  float64
 23  prev_community_2_size  78818 non-null  int64
 24  classified_llm         30263 non-null  object
dtypes: float64(6), int64(9), object(10)
memory usage: 15.0+ MB

In [15]:
df.to_csv("votacoes_com_llm.csv", index=False)